version: '3.8'

services:
  db:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - todo-db:/var/lib/mysql
      
volumes:
  todo-db: