version: '3.8'

services:
  db:
    container_name: todo-db
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - '3306:3306'
    # expose:
    #   - '3306'
    volumes:
      - todo-db:/var/lib/mysql
  todo-back:
    container_name: todo-back
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db
  todo-front:
    container_name: todo-front
    build:
      context: ./frontend
    volumes:
      - todo-front:/home/node/app/node_modules
      - ./frontend/:/home/node/app
    ports:
      - '80:3000'

volumes:
  todo-db:
  todo-front: